# Generated by Django 3.2.2 on 2021-06-30 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio_comedor', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamiliaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_familiap', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_habitacion', models.IntegerField()),
                ('descripcion_de_la_habitacion', models.CharField(max_length=1500)),
                ('disponibilidad_habitacion', models.IntegerField(choices=[[0, 'Disponible'], [1, 'No esta disponible'], [2, 'No esta disponible por estar asignado a la empresa']])),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_moneda', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_peso', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plato', models.CharField(blank=True, max_length=200, null=True)),
                ('dia_plato', models.BigIntegerField(blank=True, choices=[['', 'Seleccione el dia'], [1, 'Lunes'], [2, 'Martes'], [3, 'Miercoles'], [4, 'Jueves'], [5, 'Viernes'], [6, 'Sabado'], [7, 'Domingo']], null=True)),
                ('hora_plato', models.CharField(blank=True, choices=[['', 'Seleccione la hora'], ['10:00 AM', 'Desayuno'], ['14:00 PM', 'Almuerzo'], ['19:00 PM', 'Once']], max_length=50, null=True)),
                ('precio_plato', models.BigIntegerField(blank=True, null=True)),
                ('comedor_id_comedor', models.ForeignKey(blank=True, db_column='comedor_id_comedor', default='Seleccione un comedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.comedor')),
            ],
        ),
    ]
