# Generated by Django 3.2.2 on 2021-07-02 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='comedor_id_comedor',
            field=models.ForeignKey(blank=True, db_column='comedor_id_comedor', default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.comedor'),
        ),
    ]
