# Generated by Django 3.2.2 on 2021-07-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_alter_plato_comedor_id_comedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='comedor_id_comedor',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
