# Generated by Django 3.2.2 on 2021-07-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_alter_plato_comedor_id_comedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='disponibilidad_habitacion',
            field=models.IntegerField(choices=[[0, 'Disponible'], [1, 'No esta disponible por estar en mantenimiento'], [2, 'No esta disponible por estar asignado a la empresa']]),
        ),
    ]
