# Generated by Django 3.2.2 on 2021-07-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenpedido',
            name='fecha_rodp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
