# Generated by Django 3.2.2 on 2021-07-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_alter_ordenpedido_fecha_rodp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenpedido',
            name='fecha_codp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordenpedido',
            name='fecha_rodp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
