# Generated by Django 3.2.2 on 2021-06-30 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_inicio', models.CharField(max_length=15)),
                ('fecha_de_termino', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_de_inicio', models.DateField(blank=True, null=True)),
                ('fecha_de_termino', models.DateField(blank=True, null=True)),
                ('orden_de_compra', models.IntegerField(blank=True, null=True)),
                ('numero_de_habitacion', models.IntegerField(blank=True, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('estado_huesped', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDeCompra',
            fields=[
                ('numero_oc', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_oc', models.DateTimeField(auto_now_add=True)),
                ('valor_oc', models.BigIntegerField()),
                ('cliente_rut_empresa', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('codigo_factura', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
                ('valor_bruto', models.BigIntegerField()),
                ('valor_neto', models.BigIntegerField()),
                ('precio_total', models.BigIntegerField()),
                ('orden_de_compra_numero_oc', models.ForeignKey(db_column='orden_de_compra_numero_oc', on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.ordendecompra')),
            ],
        ),
    ]
