# Generated by Django 3.2.2 on 2021-07-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huesped',
            name='estado_huesped',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
