# Generated by Django 3.2.2 on 2021-07-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210705_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='numero_contacto',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
