# Generated by Django 3.2.2 on 2021-06-30 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.IntegerField(blank=True, null=True)),
                ('nombre_del_producto', models.CharField(max_length=50)),
                ('marca_del_producto', models.CharField(max_length=50)),
                ('descripcion_del_producto', models.CharField(max_length=1500)),
                ('fecha_de_vencimiento', models.DateField()),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('stock_critico', models.IntegerField()),
                ('id_proveedor', models.IntegerField(blank=True, null=True)),
                ('familia_producto', models.ForeignKey(blank=True, db_column='familia_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.familiaproducto')),
            ],
        ),
    ]
